
#   postgresql configurate
development:
  adapter: postgresql
  database: training_development
  host: localhost
  pool: 5

production:
  adapter: postgresql
  database: training_production
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: training_test
  host: localhost
  pool: 5